/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/group': RouteRecordInfo<
      '/albums/group',
      '/albums/group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/sister': RouteRecordInfo<
      '/albums/sister',
      '/albums/sister',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bangumi/': RouteRecordInfo<
      '/bangumi/',
      '/bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/': RouteRecordInfo<
      '/jobs/',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/advice/resume': RouteRecordInfo<
      '/jobs/advice/resume',
      '/jobs/advice/resume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/advice/schedule': RouteRecordInfo<
      '/jobs/advice/schedule',
      '/jobs/advice/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/algorithm/': RouteRecordInfo<
      '/jobs/algorithm/',
      '/jobs/algorithm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/algorithm/classic': RouteRecordInfo<
      '/jobs/algorithm/classic',
      '/jobs/algorithm/classic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/algorithm/hot-100': RouteRecordInfo<
      '/jobs/algorithm/hot-100',
      '/jobs/algorithm/hot-100',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/experience/': RouteRecordInfo<
      '/jobs/experience/',
      '/jobs/experience',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/experience/bytedance': RouteRecordInfo<
      '/jobs/experience/bytedance',
      '/jobs/experience/bytedance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/experience/meituan': RouteRecordInfo<
      '/jobs/experience/meituan',
      '/jobs/experience/meituan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/experience/meituan-ai': RouteRecordInfo<
      '/jobs/experience/meituan-ai',
      '/jobs/experience/meituan-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/experience/netcase': RouteRecordInfo<
      '/jobs/experience/netcase',
      '/jobs/experience/netcase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/experience/tencent': RouteRecordInfo<
      '/jobs/experience/tencent',
      '/jobs/experience/tencent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/': RouteRecordInfo<
      '/jobs/question/',
      '/jobs/question',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/database': RouteRecordInfo<
      '/jobs/question/database',
      '/jobs/question/database',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/java-basic': RouteRecordInfo<
      '/jobs/question/java-basic',
      '/jobs/question/java-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/java-collections-framework': RouteRecordInfo<
      '/jobs/question/java-collections-framework',
      '/jobs/question/java-collections-framework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/java-util-concurrent': RouteRecordInfo<
      '/jobs/question/java-util-concurrent',
      '/jobs/question/java-util-concurrent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/jvm/': RouteRecordInfo<
      '/jobs/question/jvm/',
      '/jobs/question/jvm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/jvm/garbage-collect': RouteRecordInfo<
      '/jobs/question/jvm/garbage-collect',
      '/jobs/question/jvm/garbage-collect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/kafka': RouteRecordInfo<
      '/jobs/question/kafka',
      '/jobs/question/kafka',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/message-queue': RouteRecordInfo<
      '/jobs/question/message-queue',
      '/jobs/question/message-queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/mysql': RouteRecordInfo<
      '/jobs/question/mysql',
      '/jobs/question/mysql',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/network': RouteRecordInfo<
      '/jobs/question/network',
      '/jobs/question/network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/os': RouteRecordInfo<
      '/jobs/question/os',
      '/jobs/question/os',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/redis/': RouteRecordInfo<
      '/jobs/question/redis/',
      '/jobs/question/redis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/question/spring-boot': RouteRecordInfo<
      '/jobs/question/spring-boot',
      '/jobs/question/spring-boot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/record': RouteRecordInfo<
      '/jobs/record',
      '/jobs/record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Emojify': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Emojify',
      '/obsidian/copilot/copilot-custom-prompts/Emojify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Explain like I am 5': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Explain like I am 5',
      '/obsidian/copilot/copilot-custom-prompts/Explain%20like%20I%20am%205',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Fix grammar and spelling': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Fix grammar and spelling',
      '/obsidian/copilot/copilot-custom-prompts/Fix%20grammar%20and%20spelling',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Generate glossary': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Generate glossary',
      '/obsidian/copilot/copilot-custom-prompts/Generate%20glossary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Generate table of contents': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Generate table of contents',
      '/obsidian/copilot/copilot-custom-prompts/Generate%20table%20of%20contents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Make longer': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Make longer',
      '/obsidian/copilot/copilot-custom-prompts/Make%20longer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Make shorter': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Make shorter',
      '/obsidian/copilot/copilot-custom-prompts/Make%20shorter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Remove URLs': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Remove URLs',
      '/obsidian/copilot/copilot-custom-prompts/Remove%20URLs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet',
      '/obsidian/copilot/copilot-custom-prompts/Rewrite%20as%20tweet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet thread': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet thread',
      '/obsidian/copilot/copilot-custom-prompts/Rewrite%20as%20tweet%20thread',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Simplify': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Simplify',
      '/obsidian/copilot/copilot-custom-prompts/Simplify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Summarize': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Summarize',
      '/obsidian/copilot/copilot-custom-prompts/Summarize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/copilot/copilot-custom-prompts/Translate to Chinese': RouteRecordInfo<
      '/obsidian/copilot/copilot-custom-prompts/Translate to Chinese',
      '/obsidian/copilot/copilot-custom-prompts/Translate%20to%20Chinese',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/': RouteRecordInfo<
      '/obsidian/template/',
      '/obsidian/template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/contest-atcoder': RouteRecordInfo<
      '/obsidian/template/contest-atcoder',
      '/obsidian/template/contest-atcoder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/contest-codeforces': RouteRecordInfo<
      '/obsidian/template/contest-codeforces',
      '/obsidian/template/contest-codeforces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/contest-leetcode': RouteRecordInfo<
      '/obsidian/template/contest-leetcode',
      '/obsidian/template/contest-leetcode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/contest-leetcode-biweekly': RouteRecordInfo<
      '/obsidian/template/contest-leetcode-biweekly',
      '/obsidian/template/contest-leetcode-biweekly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/daily': RouteRecordInfo<
      '/obsidian/template/daily',
      '/obsidian/template/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/template/record': RouteRecordInfo<
      '/obsidian/template/record',
      '/obsidian/template/record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obsidian/todo': RouteRecordInfo<
      '/obsidian/todo',
      '/obsidian/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/algorithm/interval-dp': RouteRecordInfo<
      '/posts/algorithm/interval-dp',
      '/posts/algorithm/interval-dp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/algorithm/inverse': RouteRecordInfo<
      '/posts/algorithm/inverse',
      '/posts/algorithm/inverse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/calculation/': RouteRecordInfo<
      '/posts/calculation/',
      '/posts/calculation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/calculation/steps': RouteRecordInfo<
      '/posts/calculation/steps',
      '/posts/calculation/steps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/': RouteRecordInfo<
      '/posts/contest/',
      '/posts/contest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/atc-beginner-contest-429': RouteRecordInfo<
      '/posts/contest/atc-beginner-contest-429',
      '/posts/contest/atc-beginner-contest-429',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/cf-pinely-round-5': RouteRecordInfo<
      '/posts/contest/cf-pinely-round-5',
      '/posts/contest/cf-pinely-round-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/cf-round-1040': RouteRecordInfo<
      '/posts/contest/cf-round-1040',
      '/posts/contest/cf-round-1040',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/cf-round-1042': RouteRecordInfo<
      '/posts/contest/cf-round-1042',
      '/posts/contest/cf-round-1042',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/cf-round-1051': RouteRecordInfo<
      '/posts/contest/cf-round-1051',
      '/posts/contest/cf-round-1051',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-152': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-152',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-152',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-154': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-154',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-154',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-156': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-156',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-156',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-157': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-157',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-157',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-158': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-158',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-158',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-160': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-160',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-160',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-162': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-162',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-162',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-163': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-163',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-163',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-164': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-164',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-164',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-165': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-165',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-165',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-166': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-166',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-166',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-167': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-167',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-167',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-168': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-168',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-168',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-169': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-169',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-169',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-170': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-170',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-170',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-171': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-171',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-171',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-biweekly/lc-biweekly-contest-172': RouteRecordInfo<
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-172',
      '/posts/contest/leetcode-biweekly/lc-biweekly-contest-172',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-439': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-439',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-439',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-440': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-440',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-440',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-441': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-441',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-441',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-442': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-442',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-442',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-443': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-443',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-443',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-444': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-444',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-444',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-445': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-445',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-445',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-446': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-446',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-446',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-447': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-447',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-447',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-448': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-448',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-448',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-449': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-449',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-449',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-450': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-450',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-450',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-451': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-451',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-451',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-452': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-452',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-452',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-453': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-453',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-453',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-454': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-454',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-454',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-455': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-455',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-455',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-456': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-456',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-456',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-457': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-457',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-457',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-458': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-458',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-458',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-460': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-460',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-460',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-461': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-461',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-461',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-462': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-462',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-462',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-463': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-463',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-463',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-464': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-464',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-464',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-465': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-465',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-465',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-466': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-466',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-466',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-467': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-467',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-467',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-468': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-468',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-468',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-469': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-469',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-469',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-470': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-470',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-470',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-471': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-471',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-471',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-473': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-473',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-473',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-474': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-474',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-474',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-475': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-475',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-475',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-476': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-476',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-476',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-477': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-477',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-477',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-478': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-478',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-478',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/leetcode-weekly/lc-weekly-contest-479': RouteRecordInfo<
      '/posts/contest/leetcode-weekly/lc-weekly-contest-479',
      '/posts/contest/leetcode-weekly/lc-weekly-contest-479',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/contest/question-classify': RouteRecordInfo<
      '/posts/contest/question-classify',
      '/posts/contest/question-classify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/course/20240624': RouteRecordInfo<
      '/posts/course/20240624',
      '/posts/course/20240624',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/course/CS61B': RouteRecordInfo<
      '/posts/course/CS61B',
      '/posts/course/CS61B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/database/sql-statement-execution-process': RouteRecordInfo<
      '/posts/database/sql-statement-execution-process',
      '/posts/database/sql-statement-execution-process',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/database/sql-tutorial-and-tricks': RouteRecordInfo<
      '/posts/database/sql-tutorial-and-tricks',
      '/posts/database/sql-tutorial-and-tricks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/design-pattern/singleton': RouteRecordInfo<
      '/posts/design-pattern/singleton',
      '/posts/design-pattern/singleton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java/collections': RouteRecordInfo<
      '/posts/java/collections',
      '/posts/java/collections',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java/garbage-collect': RouteRecordInfo<
      '/posts/java/garbage-collect',
      '/posts/java/garbage-collect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java/java-memory-model': RouteRecordInfo<
      '/posts/java/java-memory-model',
      '/posts/java/java-memory-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java/knowledge': RouteRecordInfo<
      '/posts/java/knowledge',
      '/posts/java/knowledge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java/package-type': RouteRecordInfo<
      '/posts/java/package-type',
      '/posts/java/package-type',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java/polymorphism': RouteRecordInfo<
      '/posts/java/polymorphism',
      '/posts/java/polymorphism',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ponder/fear': RouteRecordInfo<
      '/posts/ponder/fear',
      '/posts/ponder/fear',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ponder/fiction': RouteRecordInfo<
      '/posts/ponder/fiction',
      '/posts/ponder/fiction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/imitation-douyin-e-commerce/development-issues': RouteRecordInfo<
      '/posts/project/imitation-douyin-e-commerce/development-issues',
      '/posts/project/imitation-douyin-e-commerce/development-issues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/project-idea': RouteRecordInfo<
      '/posts/project/project-idea',
      '/posts/project/project-idea',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/trading-exchange-system/': RouteRecordInfo<
      '/posts/project/trading-exchange-system/',
      '/posts/project/trading-exchange-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/trading-exchange-system/push-module': RouteRecordInfo<
      '/posts/project/trading-exchange-system/push-module',
      '/posts/project/trading-exchange-system/push-module',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/trading-exchange-system/test-module': RouteRecordInfo<
      '/posts/project/trading-exchange-system/test-module',
      '/posts/project/trading-exchange-system/test-module',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/trading-exchange-system/trading-api-module': RouteRecordInfo<
      '/posts/project/trading-exchange-system/trading-api-module',
      '/posts/project/trading-exchange-system/trading-api-module',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/trading-exchange-system/trading-sequence-module': RouteRecordInfo<
      '/posts/project/trading-exchange-system/trading-sequence-module',
      '/posts/project/trading-exchange-system/trading-sequence-module',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/question/double-spending': RouteRecordInfo<
      '/posts/question/double-spending',
      '/posts/question/double-spending',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/question/duplicated-python-scripy': RouteRecordInfo<
      '/posts/question/duplicated-python-scripy',
      '/posts/question/duplicated-python-scripy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/question/sunlogin-internet-connect': RouteRecordInfo<
      '/posts/question/sunlogin-internet-connect',
      '/posts/question/sunlogin-internet-connect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/': RouteRecordInfo<
      '/posts/record/',
      '/posts/record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-05': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-05',
      '/posts/record/monthly/monthly-2024-05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-06': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-06',
      '/posts/record/monthly/monthly-2024-06',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-07': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-07',
      '/posts/record/monthly/monthly-2024-07',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-08': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-08',
      '/posts/record/monthly/monthly-2024-08',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-09': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-09',
      '/posts/record/monthly/monthly-2024-09',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-10': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-10',
      '/posts/record/monthly/monthly-2024-10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-11': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-11',
      '/posts/record/monthly/monthly-2024-11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2024-12': RouteRecordInfo<
      '/posts/record/monthly/monthly-2024-12',
      '/posts/record/monthly/monthly-2024-12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-01': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-01',
      '/posts/record/monthly/monthly-2025-01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-02': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-02',
      '/posts/record/monthly/monthly-2025-02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-03': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-03',
      '/posts/record/monthly/monthly-2025-03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-04': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-04',
      '/posts/record/monthly/monthly-2025-04',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-05': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-05',
      '/posts/record/monthly/monthly-2025-05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-06': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-06',
      '/posts/record/monthly/monthly-2025-06',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-07': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-07',
      '/posts/record/monthly/monthly-2025-07',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-08': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-08',
      '/posts/record/monthly/monthly-2025-08',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-09': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-09',
      '/posts/record/monthly/monthly-2025-09',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-10': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-10',
      '/posts/record/monthly/monthly-2025-10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-11': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-11',
      '/posts/record/monthly/monthly-2025-11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2025-12': RouteRecordInfo<
      '/posts/record/monthly/monthly-2025-12',
      '/posts/record/monthly/monthly-2025-12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2026-01': RouteRecordInfo<
      '/posts/record/monthly/monthly-2026-01',
      '/posts/record/monthly/monthly-2026-01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/monthly/monthly-2026-02': RouteRecordInfo<
      '/posts/record/monthly/monthly-2026-02',
      '/posts/record/monthly/monthly-2026-02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-05-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-05-1',
      '/posts/record/weekly/weekly-2024-05-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-05-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-05-2',
      '/posts/record/weekly/weekly-2024-05-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-05-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-05-3',
      '/posts/record/weekly/weekly-2024-05-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-05-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-05-4',
      '/posts/record/weekly/weekly-2024-05-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-06-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-06-1',
      '/posts/record/weekly/weekly-2024-06-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-06-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-06-2',
      '/posts/record/weekly/weekly-2024-06-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-06-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-06-3',
      '/posts/record/weekly/weekly-2024-06-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-06-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-06-4',
      '/posts/record/weekly/weekly-2024-06-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-07-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-07-1',
      '/posts/record/weekly/weekly-2024-07-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-07-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-07-2',
      '/posts/record/weekly/weekly-2024-07-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-07-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-07-3',
      '/posts/record/weekly/weekly-2024-07-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-07-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-07-4',
      '/posts/record/weekly/weekly-2024-07-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-08-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-08-1',
      '/posts/record/weekly/weekly-2024-08-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-08-2345': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-08-2345',
      '/posts/record/weekly/weekly-2024-08-2345',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-09-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-09-1',
      '/posts/record/weekly/weekly-2024-09-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-09-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-09-2',
      '/posts/record/weekly/weekly-2024-09-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-09-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-09-3',
      '/posts/record/weekly/weekly-2024-09-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-09-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-09-4',
      '/posts/record/weekly/weekly-2024-09-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-10-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-10-1',
      '/posts/record/weekly/weekly-2024-10-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-10-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-10-2',
      '/posts/record/weekly/weekly-2024-10-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-10-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-10-3',
      '/posts/record/weekly/weekly-2024-10-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-10-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-10-4',
      '/posts/record/weekly/weekly-2024-10-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-10-5': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-10-5',
      '/posts/record/weekly/weekly-2024-10-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-11-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-11-1',
      '/posts/record/weekly/weekly-2024-11-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-11-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-11-2',
      '/posts/record/weekly/weekly-2024-11-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-11-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-11-3',
      '/posts/record/weekly/weekly-2024-11-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-11-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-11-4',
      '/posts/record/weekly/weekly-2024-11-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-12-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-12-1',
      '/posts/record/weekly/weekly-2024-12-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-12-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-12-2',
      '/posts/record/weekly/weekly-2024-12-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-12-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-12-3',
      '/posts/record/weekly/weekly-2024-12-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-12-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-12-4',
      '/posts/record/weekly/weekly-2024-12-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2024-12-5': RouteRecordInfo<
      '/posts/record/weekly/weekly-2024-12-5',
      '/posts/record/weekly/weekly-2024-12-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-01-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-01-1',
      '/posts/record/weekly/weekly-2025-01-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-01-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-01-2',
      '/posts/record/weekly/weekly-2025-01-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-01-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-01-3',
      '/posts/record/weekly/weekly-2025-01-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-01-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-01-4',
      '/posts/record/weekly/weekly-2025-01-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-02-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-02-1',
      '/posts/record/weekly/weekly-2025-02-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-02-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-02-2',
      '/posts/record/weekly/weekly-2025-02-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-02-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-02-3',
      '/posts/record/weekly/weekly-2025-02-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-02-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-02-4',
      '/posts/record/weekly/weekly-2025-02-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-03-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-03-1',
      '/posts/record/weekly/weekly-2025-03-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-03-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-03-2',
      '/posts/record/weekly/weekly-2025-03-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-03-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-03-3',
      '/posts/record/weekly/weekly-2025-03-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-03-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-03-4',
      '/posts/record/weekly/weekly-2025-03-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-04-1': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-04-1',
      '/posts/record/weekly/weekly-2025-04-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-04-2': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-04-2',
      '/posts/record/weekly/weekly-2025-04-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-04-3': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-04-3',
      '/posts/record/weekly/weekly-2025-04-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/record/weekly/weekly-2025-04-4': RouteRecordInfo<
      '/posts/record/weekly/weekly-2025-04-4',
      '/posts/record/weekly/weekly-2025-04-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/document-editor-trick': RouteRecordInfo<
      '/posts/useful/document-editor-trick',
      '/posts/useful/document-editor-trick',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/git-cheat-sheet': RouteRecordInfo<
      '/posts/useful/git-cheat-sheet',
      '/posts/useful/git-cheat-sheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/git-trick': RouteRecordInfo<
      '/posts/useful/git-trick',
      '/posts/useful/git-trick',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/html-trick': RouteRecordInfo<
      '/posts/useful/html-trick',
      '/posts/useful/html-trick',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/python-helper': RouteRecordInfo<
      '/posts/useful/python-helper',
      '/posts/useful/python-helper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/python-trick': RouteRecordInfo<
      '/posts/useful/python-trick',
      '/posts/useful/python-trick',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/quick-use-githubusercontent': RouteRecordInfo<
      '/posts/useful/quick-use-githubusercontent',
      '/posts/useful/quick-use-githubusercontent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/quick-use-jupyter': RouteRecordInfo<
      '/posts/useful/quick-use-jupyter',
      '/posts/useful/quick-use-jupyter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/useful/quick-use-tar': RouteRecordInfo<
      '/posts/useful/quick-use-tar',
      '/posts/useful/quick-use-tar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/program/': RouteRecordInfo<
      '/program/',
      '/program',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/records/': RouteRecordInfo<
      '/records/',
      '/records',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sources/': RouteRecordInfo<
      '/sources/',
      '/sources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__dfb5aca93403ae8b7e1d688c26956db4/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.5_@babel+pa_728e24f9fbab54995537add117cdafcd/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'pages/albums/group.md': {
      routes:
        | '/albums/group'
      views:
        | never
    }
    'pages/albums/sister.md': {
      routes:
        | '/albums/sister'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/bangumi/index.md': {
      routes:
        | '/bangumi/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/jobs/index.md': {
      routes:
        | '/jobs/'
      views:
        | never
    }
    'pages/jobs/advice/resume.md': {
      routes:
        | '/jobs/advice/resume'
      views:
        | never
    }
    'pages/jobs/advice/schedule.md': {
      routes:
        | '/jobs/advice/schedule'
      views:
        | never
    }
    'pages/jobs/algorithm/index.md': {
      routes:
        | '/jobs/algorithm/'
      views:
        | never
    }
    'pages/jobs/algorithm/classic.md': {
      routes:
        | '/jobs/algorithm/classic'
      views:
        | never
    }
    'pages/jobs/algorithm/hot-100.md': {
      routes:
        | '/jobs/algorithm/hot-100'
      views:
        | never
    }
    'pages/jobs/experience/index.md': {
      routes:
        | '/jobs/experience/'
      views:
        | never
    }
    'pages/jobs/experience/bytedance.md': {
      routes:
        | '/jobs/experience/bytedance'
      views:
        | never
    }
    'pages/jobs/experience/meituan.md': {
      routes:
        | '/jobs/experience/meituan'
      views:
        | never
    }
    'pages/jobs/experience/meituan-ai.md': {
      routes:
        | '/jobs/experience/meituan-ai'
      views:
        | never
    }
    'pages/jobs/experience/netcase.md': {
      routes:
        | '/jobs/experience/netcase'
      views:
        | never
    }
    'pages/jobs/experience/tencent.md': {
      routes:
        | '/jobs/experience/tencent'
      views:
        | never
    }
    'pages/jobs/question/index.md': {
      routes:
        | '/jobs/question/'
      views:
        | never
    }
    'pages/jobs/question/database.md': {
      routes:
        | '/jobs/question/database'
      views:
        | never
    }
    'pages/jobs/question/java-basic.md': {
      routes:
        | '/jobs/question/java-basic'
      views:
        | never
    }
    'pages/jobs/question/java-collections-framework.md': {
      routes:
        | '/jobs/question/java-collections-framework'
      views:
        | never
    }
    'pages/jobs/question/java-util-concurrent.md': {
      routes:
        | '/jobs/question/java-util-concurrent'
      views:
        | never
    }
    'pages/jobs/question/jvm/index.md': {
      routes:
        | '/jobs/question/jvm/'
      views:
        | never
    }
    'pages/jobs/question/jvm/garbage-collect.md': {
      routes:
        | '/jobs/question/jvm/garbage-collect'
      views:
        | never
    }
    'pages/jobs/question/kafka.md': {
      routes:
        | '/jobs/question/kafka'
      views:
        | never
    }
    'pages/jobs/question/message-queue.md': {
      routes:
        | '/jobs/question/message-queue'
      views:
        | never
    }
    'pages/jobs/question/mysql.md': {
      routes:
        | '/jobs/question/mysql'
      views:
        | never
    }
    'pages/jobs/question/network.md': {
      routes:
        | '/jobs/question/network'
      views:
        | never
    }
    'pages/jobs/question/os.md': {
      routes:
        | '/jobs/question/os'
      views:
        | never
    }
    'pages/jobs/question/redis/index.md': {
      routes:
        | '/jobs/question/redis/'
      views:
        | never
    }
    'pages/jobs/question/spring-boot.md': {
      routes:
        | '/jobs/question/spring-boot'
      views:
        | never
    }
    'pages/jobs/record.md': {
      routes:
        | '/jobs/record'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Emojify.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Emojify'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Explain like I am 5.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Explain like I am 5'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Fix grammar and spelling.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Fix grammar and spelling'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Generate glossary.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Generate glossary'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Generate table of contents.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Generate table of contents'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Make longer.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Make longer'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Make shorter.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Make shorter'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Remove URLs.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Remove URLs'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet thread.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Rewrite as tweet thread'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Simplify.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Simplify'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Summarize.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Summarize'
      views:
        | never
    }
    'pages/obsidian/copilot/copilot-custom-prompts/Translate to Chinese.md': {
      routes:
        | '/obsidian/copilot/copilot-custom-prompts/Translate to Chinese'
      views:
        | never
    }
    'pages/obsidian/template/index.md': {
      routes:
        | '/obsidian/template/'
      views:
        | never
    }
    'pages/obsidian/template/contest-atcoder.md': {
      routes:
        | '/obsidian/template/contest-atcoder'
      views:
        | never
    }
    'pages/obsidian/template/contest-codeforces.md': {
      routes:
        | '/obsidian/template/contest-codeforces'
      views:
        | never
    }
    'pages/obsidian/template/contest-leetcode.md': {
      routes:
        | '/obsidian/template/contest-leetcode'
      views:
        | never
    }
    'pages/obsidian/template/contest-leetcode-biweekly.md': {
      routes:
        | '/obsidian/template/contest-leetcode-biweekly'
      views:
        | never
    }
    'pages/obsidian/template/daily.md': {
      routes:
        | '/obsidian/template/daily'
      views:
        | never
    }
    'pages/obsidian/template/record.md': {
      routes:
        | '/obsidian/template/record'
      views:
        | never
    }
    'pages/obsidian/todo.md': {
      routes:
        | '/obsidian/todo'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__dfb5aca93403ae8b7e1d688c26956db4/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'pages/posts/algorithm/interval-dp.md': {
      routes:
        | '/posts/algorithm/interval-dp'
      views:
        | never
    }
    'pages/posts/algorithm/inverse.md': {
      routes:
        | '/posts/algorithm/inverse'
      views:
        | never
    }
    'pages/posts/calculation/index.md': {
      routes:
        | '/posts/calculation/'
      views:
        | never
    }
    'pages/posts/calculation/steps.md': {
      routes:
        | '/posts/calculation/steps'
      views:
        | never
    }
    'pages/posts/contest/index.md': {
      routes:
        | '/posts/contest/'
      views:
        | never
    }
    'pages/posts/contest/atc-beginner-contest-429.md': {
      routes:
        | '/posts/contest/atc-beginner-contest-429'
      views:
        | never
    }
    'pages/posts/contest/cf-pinely-round-5.md': {
      routes:
        | '/posts/contest/cf-pinely-round-5'
      views:
        | never
    }
    'pages/posts/contest/cf-round-1040.md': {
      routes:
        | '/posts/contest/cf-round-1040'
      views:
        | never
    }
    'pages/posts/contest/cf-round-1042.md': {
      routes:
        | '/posts/contest/cf-round-1042'
      views:
        | never
    }
    'pages/posts/contest/cf-round-1051.md': {
      routes:
        | '/posts/contest/cf-round-1051'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-152.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-152'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-154.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-154'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-156.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-156'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-157.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-157'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-158.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-158'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-160.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-160'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-162.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-162'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-163.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-163'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-164.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-164'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-165.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-165'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-166.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-166'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-167.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-167'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-168.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-168'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-169.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-169'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-170.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-170'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-171.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-171'
      views:
        | never
    }
    'pages/posts/contest/leetcode-biweekly/lc-biweekly-contest-172.md': {
      routes:
        | '/posts/contest/leetcode-biweekly/lc-biweekly-contest-172'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-439.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-439'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-440.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-440'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-441.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-441'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-442.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-442'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-443.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-443'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-444.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-444'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-445.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-445'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-446.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-446'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-447.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-447'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-448.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-448'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-449.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-449'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-450.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-450'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-451.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-451'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-452.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-452'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-453.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-453'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-454.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-454'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-455.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-455'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-456.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-456'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-457.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-457'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-458.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-458'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-460.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-460'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-461.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-461'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-462.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-462'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-463.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-463'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-464.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-464'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-465.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-465'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-466.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-466'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-467.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-467'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-468.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-468'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-469.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-469'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-470.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-470'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-471.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-471'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-473.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-473'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-474.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-474'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-475.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-475'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-476.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-476'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-477.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-477'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-478.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-478'
      views:
        | never
    }
    'pages/posts/contest/leetcode-weekly/lc-weekly-contest-479.md': {
      routes:
        | '/posts/contest/leetcode-weekly/lc-weekly-contest-479'
      views:
        | never
    }
    'pages/posts/contest/question-classify.md': {
      routes:
        | '/posts/contest/question-classify'
      views:
        | never
    }
    'pages/posts/course/20240624.md': {
      routes:
        | '/posts/course/20240624'
      views:
        | never
    }
    'pages/posts/course/CS61B.md': {
      routes:
        | '/posts/course/CS61B'
      views:
        | never
    }
    'pages/posts/database/sql-statement-execution-process.md': {
      routes:
        | '/posts/database/sql-statement-execution-process'
      views:
        | never
    }
    'pages/posts/database/sql-tutorial-and-tricks.md': {
      routes:
        | '/posts/database/sql-tutorial-and-tricks'
      views:
        | never
    }
    'pages/posts/design-pattern/singleton.md': {
      routes:
        | '/posts/design-pattern/singleton'
      views:
        | never
    }
    'pages/posts/java/collections.md': {
      routes:
        | '/posts/java/collections'
      views:
        | never
    }
    'pages/posts/java/garbage-collect.md': {
      routes:
        | '/posts/java/garbage-collect'
      views:
        | never
    }
    'pages/posts/java/java-memory-model.md': {
      routes:
        | '/posts/java/java-memory-model'
      views:
        | never
    }
    'pages/posts/java/knowledge.md': {
      routes:
        | '/posts/java/knowledge'
      views:
        | never
    }
    'pages/posts/java/package-type.md': {
      routes:
        | '/posts/java/package-type'
      views:
        | never
    }
    'pages/posts/java/polymorphism.md': {
      routes:
        | '/posts/java/polymorphism'
      views:
        | never
    }
    'pages/posts/ponder/fear.md': {
      routes:
        | '/posts/ponder/fear'
      views:
        | never
    }
    'pages/posts/ponder/fiction.md': {
      routes:
        | '/posts/ponder/fiction'
      views:
        | never
    }
    'pages/posts/project/imitation-douyin-e-commerce/development-issues.md': {
      routes:
        | '/posts/project/imitation-douyin-e-commerce/development-issues'
      views:
        | never
    }
    'pages/posts/project/project-idea.md': {
      routes:
        | '/posts/project/project-idea'
      views:
        | never
    }
    'pages/posts/project/trading-exchange-system/index.md': {
      routes:
        | '/posts/project/trading-exchange-system/'
      views:
        | never
    }
    'pages/posts/project/trading-exchange-system/push-module.md': {
      routes:
        | '/posts/project/trading-exchange-system/push-module'
      views:
        | never
    }
    'pages/posts/project/trading-exchange-system/test-module.md': {
      routes:
        | '/posts/project/trading-exchange-system/test-module'
      views:
        | never
    }
    'pages/posts/project/trading-exchange-system/trading-api-module.md': {
      routes:
        | '/posts/project/trading-exchange-system/trading-api-module'
      views:
        | never
    }
    'pages/posts/project/trading-exchange-system/trading-sequence-module.md': {
      routes:
        | '/posts/project/trading-exchange-system/trading-sequence-module'
      views:
        | never
    }
    'pages/posts/question/double-spending.md': {
      routes:
        | '/posts/question/double-spending'
      views:
        | never
    }
    'pages/posts/question/duplicated-python-scripy.md': {
      routes:
        | '/posts/question/duplicated-python-scripy'
      views:
        | never
    }
    'pages/posts/question/sunlogin-internet-connect.md': {
      routes:
        | '/posts/question/sunlogin-internet-connect'
      views:
        | never
    }
    'pages/posts/record/index.md': {
      routes:
        | '/posts/record/'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-05.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-05'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-06.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-06'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-07.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-07'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-08.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-08'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-09.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-09'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-10.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-10'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-11.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-11'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2024-12.md': {
      routes:
        | '/posts/record/monthly/monthly-2024-12'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-01.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-01'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-02.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-02'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-03.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-03'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-04.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-04'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-05.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-05'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-06.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-06'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-07.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-07'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-08.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-08'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-09.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-09'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-10.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-10'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-11.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-11'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2025-12.md': {
      routes:
        | '/posts/record/monthly/monthly-2025-12'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2026-01.md': {
      routes:
        | '/posts/record/monthly/monthly-2026-01'
      views:
        | never
    }
    'pages/posts/record/monthly/monthly-2026-02.md': {
      routes:
        | '/posts/record/monthly/monthly-2026-02'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-05-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-05-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-05-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-05-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-05-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-05-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-05-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-05-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-06-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-06-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-06-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-06-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-06-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-06-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-06-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-06-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-07-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-07-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-07-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-07-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-07-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-07-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-07-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-07-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-08-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-08-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-08-2345.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-08-2345'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-09-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-09-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-09-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-09-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-09-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-09-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-09-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-09-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-10-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-10-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-10-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-10-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-10-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-10-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-10-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-10-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-10-5.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-10-5'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-11-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-11-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-11-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-11-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-11-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-11-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-11-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-11-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-12-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-12-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-12-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-12-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-12-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-12-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-12-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-12-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2024-12-5.md': {
      routes:
        | '/posts/record/weekly/weekly-2024-12-5'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-01-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-01-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-01-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-01-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-01-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-01-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-01-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-01-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-02-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-02-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-02-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-02-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-02-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-02-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-02-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-02-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-03-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-03-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-03-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-03-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-03-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-03-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-03-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-03-4'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-04-1.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-04-1'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-04-2.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-04-2'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-04-3.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-04-3'
      views:
        | never
    }
    'pages/posts/record/weekly/weekly-2025-04-4.md': {
      routes:
        | '/posts/record/weekly/weekly-2025-04-4'
      views:
        | never
    }
    'pages/posts/useful/document-editor-trick.md': {
      routes:
        | '/posts/useful/document-editor-trick'
      views:
        | never
    }
    'pages/posts/useful/git-cheat-sheet.md': {
      routes:
        | '/posts/useful/git-cheat-sheet'
      views:
        | never
    }
    'pages/posts/useful/git-trick.md': {
      routes:
        | '/posts/useful/git-trick'
      views:
        | never
    }
    'pages/posts/useful/html-trick.md': {
      routes:
        | '/posts/useful/html-trick'
      views:
        | never
    }
    'pages/posts/useful/python-helper.md': {
      routes:
        | '/posts/useful/python-helper'
      views:
        | never
    }
    'pages/posts/useful/python-trick.md': {
      routes:
        | '/posts/useful/python-trick'
      views:
        | never
    }
    'pages/posts/useful/quick-use-githubusercontent.md': {
      routes:
        | '/posts/useful/quick-use-githubusercontent'
      views:
        | never
    }
    'pages/posts/useful/quick-use-jupyter.md': {
      routes:
        | '/posts/useful/quick-use-jupyter'
      views:
        | never
    }
    'pages/posts/useful/quick-use-tar.md': {
      routes:
        | '/posts/useful/quick-use-tar'
      views:
        | never
    }
    'pages/program/index.md': {
      routes:
        | '/program/'
      views:
        | never
    }
    'pages/records/index.md': {
      routes:
        | '/records/'
      views:
        | never
    }
    'pages/sources/index.md': {
      routes:
        | '/sources/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
